name: Build, version and tag
on:
  push:
    branches:
      - main
jobs:
  build_version_tag:
    name: Build, version and tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@1.0.1
        with:
          access_key: ${{ secrets.ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          region: eu-west-1
      - name: Build image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cervantes-front
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}
          registry: ${{ steps.ecr.outputs.registry }}
          no_push: true
          dockerfile: Dockerfile
      - name: Deploy Cervantes Front
        uses: BinPar/Rancher-Action@1.2
        with:
          token: ${{ secrets.RANCHER_TOKEN }}
          context: ${{ secrets.RANCHER_CONTEXT }}
          url: ${{ secrets.RANCHER_URL }}
          args: |
            set image deployment/front-deploy-beta front-beta="402083338966.dkr.ecr.eu-west-1.amazonaws.com/cervantes-front:${{ env.RELEASE_VERSION }}" --record -n cervantes-beta
      - name: Beta update Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Version ${{ env.RELEASE_VERSION }} of ${{ github.event.repository.name }} is published in the Registry! Check it at https://cervantes-beta.binpar.cloud
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://cdn.discordapp.com/attachments/570554140514844682/831120674873278494/android-chrome-192x192.png
      - name: Beta update Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Release Failed generating version ${{ env.RELEASE_VERSION }} of ${{ github.event.repository.name }}!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://cdn.discordapp.com/attachments/570554140514844682/831120674873278494/android-chrome-192x192.png
      - name: Beta update Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Release Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://cdn.discordapp.com/attachments/570554140514844682/831120674873278494/android-chrome-192x192.png
