name: Code quality and unit testing
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  code_quality_testing:
    name: Code quality and unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo and setup
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test
