#@ load("namespace.lib.yml", "getNamespace")
#@ load("deploy.lib.yml", "getDeploy")
#@ load("service.lib.yml", "getService")
#@ load("serviceMonitor.lib.yml", "getServiceMonitor")
#@ load("ingress.lib.yml", "getIngress")
#@ load("issuer.lib.yml", "getIssuer")
#@ load("volumes.lib.yml", "getVolumeStorages", "getVolumeClaims")
#@ load("conf-map.lib.yml", "getDefaultConfigMap", "getValuesConfigMap")

--- #@ getNamespace()
--- #@ getIssuer()
#@ volumeStorages = getVolumeStorages()
#@ for/end volumeStorage in volumeStorages:
--- #@ volumeStorage
#@ volumeClaims = getVolumeClaims()
#@ for/end volumeClaim in volumeClaims:
--- #@ volumeClaim
--- #@ getDeploy()
--- #@ getService()
--- #@ getServiceMonitor()
--- #@ getIngress()
--- #@ getDefaultConfigMap()
#@ configs = getValuesConfigMap()
#@ for/end config in configs:
--- #@ config
